[/Script/FortniteGame.FortRuntimeOptions]
bEnableGlobalChat=true
bDisableGifting=false
bDisableGiftingPC=false
bDisableGiftingPS4=false
bDisableGiftingXB=false
!ExperimentalCohortPercent=ClearArray
+ExperimentalCohortPercent=(CohortPercent=100,ExperimentNum=20) # Supervised settings bug fix.
+ExperimentalCohortPercent=(CohortPercent=100,ExperimentNum=51) # Parental control bypass
+ExperimentalCohortPercent=(CohortPercent=100,ExperimentNum=62) # Social features bypass

bEnableParentalControls=false
bParentalControlsEnabled=false
bRequireParentalControlToPlay=false
bRequireParentalControlToChat=false
bEnableRatingCheck=false
bDisableRatingCheck=true
bAgeGatingEnabled=false
bEnableAgeGating=false
bLoginEpicWeb=false
 !DisabledFrontendNavigationTabs=ClearArray
+DisabledFrontendNavigationTabs=(TabName="BattlePass",TabState=EFortRuntimeOptionTabState::Hidden)
+DisabledFrontendNavigationTabs=(TabName="AthenaBattlePass",TabState=EFortRuntimeOptionTabState::Hidden)
+DisabledFrontendNavigationTabs=(TabName="Quest",TabState=EFortRuntimeOptionTabState::Hidden)
+DisabledFrontendNavigationTabs=(TabName="Quests",TabState=EFortRuntimeOptionTabState::Hidden)
+DisabledFrontendNavigationTabs=(TabName="Challenges",TabState=EFortRuntimeOptionTabState::Hidden)
+DisabledFrontendNavigationTabs=(TabName="AthenaCareer",TabState=EFortRuntimeOptionTabState::Hidden)
+DisabledFrontendNavigationTabs=(TabName="VBucks",TabState=EFortRuntimeOptionTabState::Hidden)
;+DisabledFrontendNavigationTabs=(TabName="AthenaStore",TabState=EFortRuntimeOptionTabState::Hidden)
;+DisabledFrontendNavigationTabs=(TabName="AthenaDirectAcquisition",TabState=EFortRuntimeOptionTabState::Hidden)
;+DisabledFrontendNavigationTabs=(TabName="ItemShop",TabState=EFortRuntimeOptionTabState::Hidden)
;+DisabledFrontendNavigationTabs=(TabName="Shop",TabState=EFortRuntimeOptionTabState::Hidden)

bShowStoreBanner=true
bShowVbucksCounter=true
bEnableVbucksPurchase=true
bEnableMtxPurchase=true
bEnableShowdown=true
